README
Added new subsection called “Compiling Qt Creator for Sailfish SDK on OS X” with step by step instructions on how to compile Qt and Qt Creator for Sailfish OS SDK on OS X 10.10.
Note that in order to specify the version of Qt to build, the instructions refer to an updated version of the `buildqt5.sh` script introduced in [sailfish-sdk/sdk-build-tools pull request #9](https://github.com/sailfish-sdk/sdk-build-tools/pull/9).
=> Update README with OS X build instructions

src/plugins/mer/merdeploysteps.cpp
For deployment steps, the source path of the active project is now always used as the value of the `MER_SSH_PROJECT_PATH` environment variable instead of the expanded value of the project explorer variable "%{CurrentProject:Path}".
Note that when multiple projects are open, deploying a project via the _Build | Deploy Project "myproject"_ menu action causes a technically incorrect project path value (i.e. the path of the project that contains the directory or file that is currently highlighted in the project explorer view, __not__ the path of the project set as active) to be passed in `MER_SSH_PROJECT_PATH` for the `qmake` and `make` MerSSH commands.
For these two commands, the path set in `MER_SSH_PROJECT_PATH` has to exists but the value seems to be otherwise ignored.
=> Use active project path for deployment

src/plugins/coreplugin/fancyactionbar.cpp, src/plugins/coreplugin/fancyactionbar.h
This fixes the case when action is set not visible _before_ adding with
FancyActionBar::insertAction.
(cherry picked from commit 5b7d80c032cda37ac68134a6c81ee704a1a89693)
=> Core: Fix FancyToolButton initial visibility

src/plugins/mer/mersdkdetailswidget.ui
Made the layout of `mersdkdetailswidget.ui` narrower by splitting the widest form lines “Alt source folder” and “SSH key” into two lines.
As a result, the Preferences > Mer > SDK view now only scrolls vertically, not both vertically and horizontally as before.
Further cleaned up the widget by giving all child widgets and layouts proper names and setting all form labels and form widgets to use identical size policies and layout alignments.
=> Mer: Clean up SDK details widget layout (Fixes JB#29309)

src/plugins/mer/mermanagementwebview.cpp
Observed on Windows. Management web view flashing when SDK VM is not
running. Screen blinks every 5 seconds - page auto refresh interval.
Limit auto reload to the case of VM running but not responding. For
other cases notification signals are available and already handled.
=> Mer: Avoid useless auto reload of mgmt web view

src/plugins/mer/meremulatordevice.cpp, src/plugins/mer/meremulatordevice.h
MerEmulatorDevice is not a QObject, so std::bind was used to connect a
signal to updateAvailableDeviceModels() when needed.
MerEmulatorDevice::availableDeviceModels() is rarely called so let it
call updateAvailableDeviceModels() itself as a workaround.
=> Mer: MerEmulatorDevice: only use std::bind when available

src/plugins/projectexplorer/miniprojecttargetselector.cpp
With the light background it was not obvious this is an interactive
widget; it looked like a non-interactive header of the popup widget.
=> Mini target selector: Make the kit area look less like a header

src/plugins/mer/mervirtualboxmanager.cpp
Fixes reading emulator device modes where EOL <> LF
=> Mer: Start vboxmanage getextradata with QIODevice::Text

src/plugins/help/qtwebkithelpviewer.cpp
Most probably no one ever noticed this because Qt docs set font size
explicitly in their CSS
https://code.qt.io/cgit/qt/qtbase.git/tree/doc/global/template/style/offline.css#n2
=> Help: Fix font in QtWebKitHelpView too small

src/plugins/mer/merhardwaredevicewizardpages.cpp, src/plugins/mer/merhardwaredevicewizardselectionpage.ui
1. Fix variable name
2. Add missing "not" in one message
=> Mer: Fix typo in MerHardwareDeviceWizardSelectionPage

src/plugins/mer/merrunconfiguration.cpp
With Qt 5.4 support for the deprecated QT_NO_JOURNALD_LOG and similar
variables was dropped. QT_LOGGING_TO_CONSOLE is to be used instead.
=> Mer: Add QT_LOGGING_TO_CONSOLE=1 to environment

src/plugins/mer/merrunconfigurationaspect.cpp
This should be more convenient with UpdatesAsOverlay enabled by default.
=> Mer: Add UpdateOnConnect to default QmlLive options

src/plugins/mer/mertarget.cpp
This fixes commit cca7b44b3d919c7bf958ff868d6f47af0b702f92 (Mer: Adapt
to renamed Sailfish OS build engine and emulator)
Quoting a variable assignment with spaces is not needed in Windows CMD.
Moreover quotes become part of the assigned value.
=> Mer: Fixup Adapt to renamed Sailfish OS build engine and emulator

src/plugins/projectexplorer/miniprojecttargetselector.cpp
Eliding two strings can hide just the part where they differ. When this
happens, try the other text elide modes.
=> MiniProjectTargetSelector: Dynamically choose best elide mode

src/tools/merssh/deploycommand.cpp, src/tools/merssh/makecommand.cpp, src/tools/merssh/qmakecommand.cpp, src/tools/merssh/rpmcommand.cpp
With this mb2 will issue a warning when qtc_* macros are missing from
the .spec file.
=> Merssh: pass --pedantic to mb2

src/plugins/qtsupport/gettingstartedwelcomepage.cpp
This would cause a build error with Sailfish/Mer projects where the SDK
installation directory is usually out of the configured projects
directory.
=> QtSupport: Copy examples to a writable location unconditionally

src/plugins/qmakeandroidsupport/QmakeAndroidSupport.json.in
This hidden plugin caused loading of the Android plugin which was
already marked as experiemntal.
=> Mark QmakeAndroidSupport plugin as experimental

src/plugins/mer/meremulatormodedialog.cpp
meremulatormodedialog: Fix compile error
```
meremulatormodedialog.cpp:54:32:
error: invalid use of incomplete type ‘class QAction’
m_action(new QAction(this)),
^
In file included from /QT/5.11.1/gcc_64/include/QtGui/QList:1:0,
from ../../plugins/projectexplorer/abi.h:30,
from merdevice.h:26,
from meremulatordevice.h:26,
from meremulatormodedialog.h:36,
from meremulatormodedialog.cpp:30:
/Qt/5.11.1/gcc_64/include/QtGui/qevent.h:62:7:
note: forward declaration of ‘class QAction’
```
=> meremulatormodedialog: Fix compile error

src/plugins/qmakeprojectmanager/qmakeparsernodes.cpp, src/plugins/qmakeprojectmanager/qmakeparsernodes.h, src/shared/proparser/profileevaluator.cpp, src/shared/proparser/profileevaluator.h
If e.g. DISTFILES contains wildcards, watch the directory for changes.
Fixes: QTCREATORBUG-21603
Change-Id: Ia6e8c94ab7b74e0404776ba1d7d9b10eb3b643de
Reviewed-by: Oswald Buddenhagen <oswald.buddenhagen@qt.io>
Reviewed-by: Tobias Hunger <tobias.hunger@qt.io>
Reviewed-by: Orgad Shaneh <orgads@gmail.com>
(cherry picked from commit 76262814b6a10604cf84c3ecc85b2792af1b942d)
=> QmakeProjectManager: Watch wildcard directories for changes

src/share/qtcreator/data.pro
lrelease external tool does not work, and it is not needed because
lrelease is executed during build
=> Remove external tool lrelease

src/tools/merssh/rpmvalidationcommand.cpp
rpmvalidation.sh uses optional target parameter to execute validator
in target instead of build engine
=> MerSsh: use target parameter in rpmvalidation command

src/plugins/mer/merdevicexmlparser.cpp, src/plugins/mer/merdevicexmlparser.h, src/plugins/mer/mersdkmanager.cpp
The settings UI allows one to change the ssh port of a device. This
setting was not used by the build engine.
=> Mer: Write ssh port to devices.xml

src/plugins/mer/merdeploysteps.cpp
Lower case should be used when not referring to a specific instance.
=> Mer: Use lower case "build target"

src/plugins/mer/mersdk.cpp, src/plugins/mer/mertarget.cpp, src/plugins/mer/mertarget.h
Sometimes non-mer kits were visible in the configuration wizard, e.g.
"Desktop" kit. These could not be used for Sailfish OS projects, so it's
better to deregister them.
=> Mer: Use kits added with sdktool instead of creating new ones

src/plugins/mer/meremulatormodedialog.cpp, src/plugins/mer/meremulatormodedialog.h
If m_dialog parent is deleted while exec is running, also m_dialog is
deleted. Accessing m_dialog after exec in these cases may crash.
=> Mer: Don't use MerEmulatorModeDialog::m_dialog after calling exec

src/plugins/qmakeprojectmanager/qmakeparsernodes.cpp, src/plugins/qmakeprojectmanager/qmakeparsernodes.h
When a file is saved, the directory is also touched. If files are not
added or removed, it is not necessary to reparse the project.
Change-Id: I718db68362d41ba936629be880f739ad79b8cb6f
Fixes: QTCREATORBUG-22361
Reviewed-by: Christian Kandeler <christian.kandeler@qt.io>
(cherry-picked from commit ecd386c67b3e3c00546df4624b53a5c36e7623ff)
=> QmakePM: Only schedule update when files are added/removed. JB#45377

src/plugins/mer/meremulatordevice.cpp, src/plugins/mer/meremulatordevice.h
After introducing possibility to install multiple emulators, the
sharedConfigPath of an emulator is no more equal to the sharedConfigPath
of the build engine, while that one is searched for the private keys
later.
=> Mer: Fix target path for emulator's private SSH keys

src/plugins/mer/meremulatordevicewizardpages.cpp
MerEmualtorVMPage::handleEmulatorVmChanged sets the first snapshot
as factory snapshot. If there are no snapshots, this would cause
Qt Creator to crash.
=> Mer: Not initialize factory snapshot when no snapshots exist

dist/installer/mac/qt.conf
Fixes qtc-askpass failing to find Qt platform plugin.
Not using Prefix=.. as none of the other qt.conf variants uses it.
=> Fix qt.conf for macOS

src/plugins/mer/meremulatormodedialog.cpp, src/plugins/mer/mervirtualboxmanager.cpp, src/plugins/mer/mervirtualboxmanager.h
Starting from 3.1.0 the Sailfish OS Emulator uses vboxdrmfb driver,
which uses GUI/LastGuestSizeHint for determining the video mode to use.
Also, in order to show the full screen even when it does not fit the
host display, Auto-resize Guest Display must be disabled.
=> Mer: Set last guest size hint when changing emulator mode

src/plugins/mer/merdeployconfiguration.cpp
MerRsyncDeployConfigurationFactory added MerMb2RpmDeployStep instead of
MerMb2RsyncDeployStep, which caused the "Deploy by Copying Binaries" to
fail.
=> Mer: add correct deploy step in MerRsyncDeployConfigurationFactory

src/app/main.cpp
Fix problem that in Windows the "settings" folder is installed on the disk from which the installer was started
Probably fix Jb45141
=> Fix save settings on first start on Windows

src/plugins/mer/meremulatormodedetailswidget.cpp
Changing the text makes the cursor jump to the end of the line. It is
not necessary to change the text if the old text is the same as the new.
=> Mer: Check that nameLineEdit has different text before changing it

src/libs/sfdk/buildengine.cpp, src/libs/sfdk/sfdkconstants.h, src/plugins/mer/mersdkkitinformation.cpp, src/tools/merssh/main.cpp
Using just the name localhost caused at least git ssh to try to
connect first via IPv6, causing unwanted delays.
=> Sfdk: Hardcode IPv4 address for build engine and emulator

src/plugins/coreplugin/documentmanager.cpp, src/plugins/coreplugin/documentmanager.h, src/plugins/coreplugin/mainwindow.cpp, src/plugins/coreplugin/mainwindow.h
Fixes: QTCREATORBUG-22072
Change-Id: I6c84e0004d1ada27bfcec59f509d066f1b03ca2c
Reviewed-by: Eike Ziller <eike.ziller@qt.io>
=> Disable "Save All" when there are no documents to be saved

src/libs/sfdk/vmconnection.cpp, src/libs/sfdk/vmconnection_p.h
Wait until `systemctl is-system-running` stops saying "starting".
=> Sfdk: Disallow connections to VMs while starting

src/tools/merssh/command.cpp
This ensures that Qt from PATH is never displayed when configuring
projects.
This commit is not planned to be sent upstream.
=> MerSSH: Map also tool paths in CMake files

src/plugins/projectexplorer/deploymentdata.cpp
The original approach does not work with absolute file paths on Windows
=> ProjectExplorer: Split deployment data using last colon on the line

src/plugins/cmakeprojectmanager/tealeafreader.cpp, src/plugins/cmakeprojectmanager/tealeafreader.h
Trying forcefully stop cmake is not a good idea with merssh, for two reasons:
1) It doesn't work, cmake keeps on running on the build engine
2) It kills merssh, which results in cmake files not having their paths mapped.
Therefore, it's better to just let cmake run to finish, ignore the results, and start again.
This might not be perfect solution, but it's going to be a temporary one anyway: upstream is getting rid of the whole TeaLeafReader in 4.13. This probably means that we are going to have to figure out how to run cmake in server mode inside build targets, translating paths on the fly...
=> TeaLeafReader: Don't forcefully stop CMake when restarting

src/plugins/mer/merdeploysteps.cpp
sfdk takes care of reverse mapping of paths, so we should not do it
here. Also, as paths under Windows don't start with '/', we must not
use it in the regexp.
=> Mer: Fix parsing rpm command output after moving to sfdk

src/tools/merssh/command.cpp
Without EOL at EOF qtc incorrectly reads the variable with last
character removed.
(cherry picked from commit f15d78167b4af5f73dc95b019bca8ca112eef4b8)
=> MerSsh: Fix false detection of QT_QMAKE_EXECUTABLE change

src/plugins/projectexplorer/miniprojecttargetselector.cpp
commit 71ad0a2270f439a9425e2d273d8c86fa7cc29256 used std::array, but
didn't add the corresponding header. When compiled with Visual Studio
2019, the header is not included from anywhere else.
=> MiniProjectTargetSelector: include <array>

src/tools/merssh/cmakecommand.cpp
QtCreator uses '/' as separator when constructing the qtcsettings.cmake
parameter, even on Windows
=> MerSsh: Always expect '/' as directory separator for qtcsettings.cmake

src/libs/sfdk/sdk.cpp
By default, QSettings reads and writes settings using the General group.
If group is set to General using beginGroup(), it uses %General instead,
which is not what we want.
=> Sfdk: Expect the General group to be default when reading settings

src/tools/merssh/main.cpp
The wrapper scripts use single quotation mark for quoting arguments also
in Windows. QtcProcess::splitArgs does not interpret single quotation
marks with OsTypeWindows.
=> MerSsh: Always use OsTypeLinux when unquoting arguments

src/plugins/projectexplorer/miniprojecttargetselector.cpp, src/plugins/projectexplorer/projectconfiguration.cpp, src/plugins/projectexplorer/projectconfiguration.h, src/plugins/projectexplorer/projectconfigurationmodel.cpp, src/plugins/projectexplorer/runconfiguration.cpp, src/plugins/projectexplorer/runcontrol.cpp
The run configuration name defaults to "<executable> (on <device>)".
When another device is selected e.g. using the MiniProjectTargetSelector
or Kits->Device option, the <device> part in run configuration name is
not updated and keeps referring to the initially selected device.
Change-Id: Idda828b7f33b754d3b50268d7417c9a2790db30e
Reviewed-by: Christian Kandeler <christian.kandeler@qt.io>
(cherry picked from commit 4d1b7d4c3ded97bd4480532075c310ce09111d6f)
=> Update run configuration after device change

src/plugins/mer/merqmakebuildconfiguration.cpp, src/plugins/mer/merqmakebuildconfiguration.h
QMake should never be run on the host, so we don't want the user to
accidentally enable this
=> Mer: Disable and hide RunSystemFunction on project config

src/plugins/projectexplorer/devicesupport/deviceprocesslist.cpp
Fetching process list from remote device can take a long time, which
might cause impatient users think that something is wrong and cancel
the listing.
=> ProjectExplorer: Display message while fetching process list

src/libs/sfdk/virtualmachine.cpp
The UI is waiting for the done signals from initGuest, so we need to do
something, even when we are doing nothing.
=> Sfdk: enqueue checkpoint in VirtualMachinePrivate::doInitGuest()

src/libs/sfdk/virtualmachine.cpp, src/libs/sfdk/vmconnection.cpp
...to VmConnection, where the BatchComposer is instantiated.
=> Sfdk: Move checkpoint enqueuing from VirtualMachinePrivate

share/qtcreator/sfdk/modules/20-building-mb2/doc/command.build-init.adoc
The state directory may have been left in a wrong place in the past, it makes sense to hint the user that it's safe to remove it.
=> Sfdk: Hint about offending state directory in build-init help

src/libs/sfdk/vboxvirtualmachine.cpp
VirtualBox 7.0 no longer uses GUI/LastGuestSizeHint, so we need to set both in order to make sure window size is correct
=> Sfdk: Set GUI/LastNormalWindowPosition on setVideoMode
